In [51]:
import pandas
from sklearn.preprocessing import MinMaxScaler
import numpy as np

import seaborn as sn
import matplotlib.pyplot as plt
import pandas
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


import xlwt
from xlwt import Workbook


dataframe = pandas.read_table('mixed200.txt')
  # file name need to be change depending on the condition
data = dataframe.drop("No.", axis=1)
  # depending on the features we have to cut it
data = data.drop("StdPageRank", axis=1)
data = data.drop("VarPageRank", axis=1)
dataset = data.values





  
# Workbook is created
wb = Workbook()
  
# add_sheet is used to create sheet.
sheet1 = wb.add_sheet('Sheet 1')


l = len(data)
training = int(l*.7)
print(training)
  # validating =5534
testing = l - training    #24749 


X = dataset[:,0:]

labels = []
for i in range (0,l):
  if X[i][9] == 1:
    labels.append(1)
  else:
    labels.append(0)

features = X[0:l,0:9]


print("Attacked------"+str(labels.count(1)))
print("Attackfree----->"+str(labels.count(0)))

adv = 10000

labels1 = []

for j in range(30):

  labels1 = []

  for i in range(adv):
    labels1.append(1- labels[i])
  
  for i in range(adv,len(labels)):
    labels1.append(labels[i])

#print(labels)





  train, test,y_train,y_test =features[0:training],features[training:training+testing],labels1[0:training],labels1[training:training+testing]













  print("###############################################caplino#####################")

    # Initialize our classifier
  gnb = GaussianNB()

    # Train our classifier
  
  model = gnb.fit(train, y_train)
  preds = gnb.predict(test)

  print(y_test.count(1))
  print(y_test.count(0))

    
    # Evaluate accurac
  val = accuracy_score(y_test, preds)
  sheet1.write(j, 0, adv)
  sheet1.write(j, 1, val)
  wb.save("output.xls")

  print(val)


  cm = confusion_matrix(y_test, preds)

  cm = cm.T

  

  print(cm)

  if adv >= 28000:
    adv+=100
  else:
    adv += 1000




57747
Attacked------58834
Attackfree----->23663
###############################################caplino#####################
17627
7123
0.9672727272727273
[[ 6836   523]
 [  287 17104]]
###############################################caplino#####################
17627
7123
0.9673535353535353
[[ 6805   490]
 [  318 17137]]
###############################################caplino#####################
17627
7123
0.9674747474747475
[[ 6778   460]
 [  345 17167]]
###############################################caplino#####################
17627
7123
0.9667474747474748
[[ 6745   445]
 [  378 17182]]
###############################################caplino#####################
17627
7123
0.9674343434343434
[[ 6716   399]
 [  407 17228]]
###############################################caplino#####################
17627
7123
0.9662626262626263
[[ 6663   375]
 [  460 17252]]
###############################################caplino#####################
17627
7123
0.9646060606060606
[[ 6612   365]
 [  511 1