In [ ]:
!unzip /content/DoS_dataset.csv.zip

Archive:  /content/DoS_dataset.csv.zip
  inflating: DoS_dataset.csv         
   creating: __MACOSX/
  inflating: __MACOSX/._DoS_dataset.csv  


In [ ]:
import numpy as np


fileId = open('/content/DoS_dataset.csv', 'r')

detectList = []
counter = 1
graphList = []
ultimateGraphList = [] 
utlimateaDetectionList = []
graphCounter = 0


messageSize = 2000

for line in fileId:

  Xpartition = line.split()[0].split(',')
  node = Xpartition[1]
  attackCheck = Xpartition[len(Xpartition)-1]



  graphList.append(node)
  detectList.append(attackCheck)
  

  if len(graphList) == messageSize: 
    ultimateGraphList.append(graphList)
    utlimateaDetectionList.append(detectList)
   

    graphList = []
    detectList = []
   
   

ugl = ultimateGraphList

udl = utlimateaDetectionList

print(len(ugl))
print(len(udl))

print(ugl[0])
print(len(ugl[0]))
print(len(udl[0]))
print(udl[0])
print(udl[3])

1832
1832
['0316', '018f', '0260', '02a0', '0329', '0545', '0002', '0153', '02c0', '0130', '0131', '0140', '0350', '043f', '0370', '0440', '0316', '018f', '0260', '02a0', '0329', '04f0', '0545', '0430', '04b1', '01f1', '0153', '0002', '02c0', '0350', '0130', '0131', '0140', '0370', '043f', '0440', '05f0', '018f', '0260', '02a0', '0316', '0329', '0545', '0002', '0153', '02c0', '0130', '0131', '0140', '0350', '043f', '0370', '00a0', '00a1', '0440', '0316', '018f', '0260', '02a0', '0329', '04f0', '0545', '0430', '04b1', '01f1', '0153', '0002', '02c0', '0350', '0130', '0131', '0140', '0370', '043f', '0440', '0316', '018f', '0260', '02a0', '0329', '0545', '0002', '0153', '02c0', '0130', '0131', '0140', '0350', '043f', '0370', '0440', '0316', '018f', '0260', '02a0', '0329', '04f0', '0545', '0690', '0430', '04b1', '01f1', '0153', '0002', '02c0', '0350', '0130', '0131', '0140', '0370', '043f', '0440', '0316', '018f', '0260', '02a0', '0329', '0545', '0002', '0153', '02c0', '0130', '0131', '0140

In [ ]:
#Making graph from the 200 sequential of id and store them in a file as Graph adjacent list
from collections import defaultdict
import networkx as nx
import matplotlib.pyplot as plt
import random

gAttackfree=nx.DiGraph()
gAttacked = nx.DiGraph()

lenugl = len(ugl)

fileW = open("DosAttackGraph.txt","w")

counter = 0
gAttackfreeCounter = 0
gAttackedCounter = 0

isNotDone1 = True
isNotDone2 = True 
gAttackfree=nx.DiGraph()
gAttacked = nx.DiGraph()

for i in range(0,lenugl):
  fileW.write("Graph No: "+str(i+1))
  fileW.write("\n")
  dicGraph = defaultdict(list)
  attackFree = True

  

  for j in range (0, len(ugl[i])-1):
    dicGraph[str(ugl[i][j])].append((ugl[i][j+1]))

  for j in range (0,len(udl[i])):
    if str(udl[i][j]) == 'T': 
      attackFree = False
      break

  

  
  fileW.write("Attack Free: "+str(attackFree)+"\n")

  for key, val in dicGraph.items():
    fileW.write(str(key) + (" ---> "))
    for m in range(0, len(val)):
      fileW.write(val[m]+"\t")
    fileW.write("\n")


print(counter)
print(gAttackfreeCounter)
print(gAttackedCounter)

fileW.close()

#print(len(list(gAttackfree)))


0
0
0


In [ ]:
#Getting all the features

import networkx as nx
import hashlib
import numpy as np

#Function for tracing the attacked and attackfree graph. Return a list which 
#contation the info that a graph is attacked or attack
def getAttackFreelist(filename):
  attacFreekList = []
  file_ = open(filename, 'r')


  graphCounter = 0
  while True: 
  
    # Get next line from file 
      line = file_.readline() 
  
    # if line is empty 
    # end of file is reached 
      if not line: 
          break
    

    
      graph_number = line[0:5]
    
      if graph_number == "Graph":
      #print(graph_number+str(graphCounter))
        graphCounter += 1
        line = file_.readline()
        attacFreekList.append(line.split())

  
  file_.close()
  print(len(attacFreekList))
  print(attacFreekList)
  return attacFreekList


def getFeatures(filename):

  attackFreeList = getAttackFreelist(filename)
  file_ = open(filename, 'r')

  graphList = []
  ultimate_graphList = []  
  graphCounter = 0
  while True: 
  
    # Get next line from file 
      line = file_.readline() 
  
    # if line is empty 
    # end of file is reached 
      if not line: 
          break
    

    
      graph_number = line[0:5]
    
      if graph_number == "Graph":
      #print(graph_number+str(graphCounter))
        graphCounter += 1
        line = file_.readline()
        line = file_.readline()

        if graphCounter >= 2:
          ultimate_graphList.append(graphList)
          graphList = []


    
      list1 = line.split()
      graphList.append(list1)



  ultimate_graphList.append(graphList)
    
  file_.close()

  list_All_Feature_Set = []
 
  filetowrite = filename[:-4]+"_GraphFeatures.txt"
  file1 = open(filetowrite,'w')

  graphNumber = len(ultimate_graphList)
# Iterating every graph
  for i in range(0,graphNumber):

    G = nx.DiGraph()
    graphEdgeNumber = len(ultimate_graphList[i])
     # defining variable for detecting max pagerank
  #making the graph
    indegree = 0
    outdegree = 0
    
    for j in range(0,graphEdgeNumber):
      vertexConnectionLength = len(ultimate_graphList[i][j])

      for k in range(2,vertexConnectionLength):
      
      
        G.add_edge(ultimate_graphList[i][j][0],ultimate_graphList[i][j][k])
    

    weighted_Feature_Set = nx.pagerank(G)
    
    edge = G.number_of_edges()
    node = G.number_of_nodes()

    
    temp_list = list(weighted_Feature_Set.values())
    median_pagerank_vertices = np.median(temp_list)
    maximum_pagerank_vertex = np.max(temp_list)
    minimum_pagerank_vertex = np.min(temp_list)
    std_pagerank = np.std(temp_list)
    varpagerank = np.var(temp_list)


    if i == 0:
      file1.write("No."+"\t"+"Nodes\t"+"Edges\t"+"MaximumIndegree\t"+"MinimumIndegree\t"+"MaximumOutdegree\t"+
                  "MinimumOutdegree\t"+	
                  "MedianPagerank\t"+"MaximumPagerank\t"+"MininumPagerank\t"+"StdPageRank\t"+
                  "VarPageRank\t"+"State\n")

    file1.write(str(i+1)+"\t")
    counter = 0
    in_deg = []
    out_deg = []
    for key,val in weighted_Feature_Set.items():
      in_deg.append(G.in_degree(key))
      out_deg.append(G.out_degree(key))
    
    maxInd = np.max(in_deg)
    minInd = np.min(in_deg)
    maxOut = np.max(out_deg)
    minOut = np.min(out_deg)
    file1.write(str(node)+"\t") 
    file1.write(str(edge)+"\t")
    file1.write(str(maxInd)+str("\t")+str(minInd)+str("\t"))
    file1.write(str(maxOut)+str("\t")+str(minOut)+str("\t"))
    
    file1.write(str(median_pagerank_vertices)+str("\t")+str(maximum_pagerank_vertex))
    file1.write(str("\t")+str(minimum_pagerank_vertex)+str("\t")+str(std_pagerank)+"\t"+
                str(varpagerank)+"\t"+
                str(attackFreeList[i][2])+"\n")

  


  file1.close()
getFeatures('DosAttackGraph.txt')



1832
[['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Free:', 'False'], ['Attack', 'Fr

In [ ]:
#Applying the GNB and getting the accuracy and confusion matrix

import seaborn as sn
import matplotlib.pyplot as plt
import pandas
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


# load dataset
dataframe = pandas.read_table('/content/DosAttackGraph_GraphFeatures.txt')
data = dataframe.drop("No.", axis=1)
data = data.drop("StdPageRank", axis=1)
data = data.drop("VarPageRank", axis=1)
dataset = data.values



# split into input (X) and output (Y) variables


l = len(ugl)
X = dataset[:,0:]
# print(X.shape)
labels = []
for i in range (0,l):
  if X[i][9] == True:
    labels.append(0)
  else:
    labels.append(1)

features = X[0:l,0:9]


# Split our data
train, test, train_labels, test_labels = train_test_split(features,
                                                            labels,
                                                            test_size=0.33,
                                                            random_state= 898)#

  # Initialize our classifier
gnb = GaussianNB()

  # Train our classifier
model = gnb.fit(train, train_labels)
preds = gnb.predict(test)

print(test_labels.count(1))
print(test_labels.count(0))

  
  # Evaluate accurac
print(accuracy_score(test_labels, preds))

cm = confusion_matrix(test_labels, preds)

cm = cm.T

print(cm)



309
296
0.9917355371900827
[[294   3]
 [  2 306]]


In [ ]:
# cm = [[1612 ,  10],
#  [   5  ,793]]


tp = cm[0][0]
tn = cm[1][1]
fp = cm[0][1]
fn = cm[1][0]

re = tp/(tp+fn)
pr = tp/(tp+fp)
f1 = 2*pr*re/(pr+re)
fpr = fp / (fp+tn)
print("pr.........."+str(pr))
print("re----"+str(re))

print("f1===="+str(f1))
print("fpr====="+ str(fpr))
print((tp+tn)/(tp+tn+fp+fn))

pr..........0.98989898989899
re----0.9932432432432432
f1====0.9915682967959528
fpr=====0.009708737864077669
0.9917355371900827


In [ ]:
71002
170939
0.991287131986724
[[170760   1929]
 [   179  69073]]
 5

35791
85180
0.9906010531449686
[[84065    22]
 [ 1115 35769]]
 10


3659
8438
0.9962800694387038
[[8424   31]
 [  14 3628]]
100


1832
4217
0.993387336749876
[[4197   20]
 [  20 1812]]

803
1617
0.993801652892562
[[1612   10]
 [   5  793]]
 500



 464
746
0.9917355371900827
[[743   7]
 [  3 457]]
 1000



 309
296
0.9917355371900827
[[294   3]
 [  2 306]]
 2k

 175
67
1.0
[[ 67   0]
 [  0 175]]
 5k


 88
33
1.0
[[33  0]
 [ 0 88]]
 10k

In [ ]:
cm =[ [[170760 ,  1929],
 [179 , 69073]],

 [[84065   , 22],
 [ 1115, 35769]],

[[8424 ,  31],
 [  14, 3628]],

 [[4197 ,  20],
 [  20 ,1812]],

 [[1612  , 10],
 [   5  ,793]],

[[743 ,  7],
 [  3 ,457]],


 [[ 67 ,  0],
 [  0 ,175]],

 [[33,  0],
 [ 0, 88]]
]

for i in range(len(cm)):

  tp = cm[i][0][0]
  tn = cm[i][1][1]
  fp = cm[i][0][1]
  fn = cm[i][1][0]

  re = tp/(tp+fn)
  pr = tp/(tp+fp)
  f1 = 2*pr*re/(pr+re)
  fpr = fp / (fp+tn)


  mcc = (tp*tn-fp*fn)/((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn))**.5

  fdr = fp/(fp+tp)

  # print("pr.........."+str(pr))
  # print("re----"+str(re))

  # print("f1===="+str(f1))
  # print("fpr====="+ str(fpr))
  print("mcccccc--------->" +str(mcc))
  #print("fdr======="+str(fdr))
  # print((tp+tn)/(tp+tn+fp+fn))

mcccccc--------->0.9789880325873227
mcccccc--------->0.9778659028555149
mcccccc--------->0.991178167512607
mcccccc--------->0.9843402613459972
mcccccc--------->0.9860106010676708
mcccccc--------->0.9825172905181248
mcccccc--------->1.0
mcccccc--------->1.0
