In [ ]:
from numpy import random
import matplotlib.pyplot as plt 
import numpy as np
import xlwt 
from xlwt import Workbook 




x_t = random.randint(10, size=(row, col))

print(x_t)
arr = x_t

[[9 4 8 8 9 3 9 0 9 4]
 [2 5 1 5 0 3 2 5 3 7]
 [9 7 5 7 4 8 8 1 3 1]
 [5 4 4 1 8 1 3 1 7 0]
 [0 8 9 1 7 8 6 7 7 4]
 [8 0 6 7 0 0 3 4 8 5]]


In [ ]:
#25 graphs
from numpy import random
import matplotlib.pyplot as plt 
import numpy as np
import xlwt 
from xlwt import Workbook 
import matplotlib.pyplot as plt
ultimateSol = []


def squrMinus(x,y):
  return  (y-x)

def squrPlus(x,y):
  return y+x






def objectiveValuesList(x,y,a,b):
  L1 = []


  for i in range(len(x)):
    if a == 0:
      L1.append([squrMinus(x[i],y[i]),i])
    else:
      L1.append([squrPlus(x[i],y[i]),i])

  
  sortedPairsObjective = sorted(L1,key=lambda x: (x[0]),reverse=False)
  print(sortedPairsObjective)
  
  return sortedPairsObjective






def findAllpairsObjective(x_t):

  allPairsObjective = []
  print(len(x_t))
  for i in range(0,6):
    for j in range(i+1,6):
      if i!=j:
        allPairsObjective.append(objectiveValuesList(x_t[i],x_t[j],i,j))



  
  return allPairsObjective

def getSol(sList):
  setAllPairObjective = sorted(set(sList))
  sol= []
  for i in range(len(setAllPairObjective)):
    sol.append([setAllPairObjective[i],sList.count(setAllPairObjective[i])])

  sol = sorted(sol,key=lambda x: (x[1]),reverse=True)
  print(sol)

  return sol


def printSol(sol,a):

  for i in range(a,len(sol)):
    output = ""
    if sol[i][1] == sol[a][1]:
      index = sol[i][0]
      output=str(index)+"--->"
      for j in range(len(x_t.T[index])):
        output+="{0:.7f}".format(x_t.T[index][j])+"\t"
      print(output)
    else:
      return i



def writeExcel(sol):
  wb = Workbook() 
  sheet1 = wb.add_sheet('Sheet') 
  
  checkList = []
  r = 0
  for i in range(len(sol)):
    output = ""
    storeOutput = ""
    index = sol[i][0]
    
    outCore="{0:.7f}".format(arr.T[index][0])
    outAsr = "{0:.7f}".format(arr.T[index][1])
    outWire = "{0:.7f}".format(arr.T[index][2])
    outClk = "{0:.7f}".format(arr.T[index][3])
    outDrc = "{0:.7f}".format(arr.T[index][4])
    outArea = "{0:.7f}".format(arr.T[index][5])
    storeOutput = outCore+outAsr+outWire+outClk+outDrc+outArea
    #print(str(index)+"\t"+outCore+"\t"+outAsr+"\t"+outWire+"\t"+outClk+"\t"+outDrc+"\t"+outArea)
    if checkList.count(storeOutput) != 1 and sol[i][1] >= 1:
      #print(str(index)+"\t"+outCore+"\t"+outAsr+"\t"+outWire+"\t"+outClk+"\t"+outDrc+"\t"+outArea)
      ultimateSol.append([index,arr.T[index][0],arr.T[index][1],arr.T[index][2],arr.T[index][3]
                          ,arr.T[index][4],arr.T[index][5]])
      sheet1.write(r, 0, str(index)) 
      sheet1.write(r, 1, outCore) 
      sheet1.write(r, 2, outAsr) 
      sheet1.write(r, 3, outWire) 
      sheet1.write(r, 4, outClk) 
      sheet1.write(r, 5, outDrc) 
      sheet1.write(r, 6, outArea) 
      checkList.append(outCore+outAsr+outWire+outClk+outDrc+outArea)
      r += 1
    
  wb.save('15valusmax1.xls') 

def solIntermediate(allPairsObjective):

  sList = []
  print(allPairsObjective)
  for i in range(len(allPairsObjective)):
    max = allPairsObjective[i][0][0]
    print(max)
    counter = 0
    subList = []
    for j in range(len(allPairsObjective[i])):
      if allPairsObjective[i][j][0] == max:
        subList.append(allPairsObjective[i][j][1])
    sList+=subList

  print('all pairs objectiuve')
  print(sList)
  return sList


def drawCurve(x,y,m,n,a,b,c,d):
  s1,s2 = 160,70
  plt.figure(figsize=(s1,s2))
  s = 20
  plt.scatter(x,y, marker = 'o', s = 2400) # for changing it to scatter plt.scatter() and keep the s which is point size
  
  #plt.plot(x,y,)  # for changing it to striaght line plt.plot() and omit the s which is point size
  ans = 200
  for i in range(len(x)):
    plt.annotate("("+str(x[i])+","+str(y[i])+")", (x[i],y[i]), size = ans)
  f = 160
  plt.xlabel('Variable 1',fontsize = f, fontweight = 'bold')
  plt.ylabel('Variable 2',fontsize = f, fontweight = 'bold')
  plt.tick_params(labelsize=30)
  plt.savefig('xvsy.pdf', bbox_inches = 'tight')


  plt.figure(figsize=(s1,s2))
  #plt.scatter(x,y, s= 20) # for changing it to scatter plt.scatter() and keep the s which is point size
  plt.plot(m,n,marker='o',markersize=80)  # for changing it to striaght line plt.plot() and omit the s which is point size
 
  for i in range(len(x)):
    plt.annotate("("+str(m[i])+","+str(n[i])+")", (m[i],n[i]), size = ans)
  
  plt.xlabel('Sample no',fontsize = f, fontweight = 'bold')
  plt.ylabel('Variable 2 - Variable 1',fontsize = f, fontweight = 'bold')
  plt.tick_params(labelsize=30)
  plt.savefig('y-x.pdf', bbox_inches = 'tight')




  plt.figure(figsize=(s1,s2))
  #plt.scatter(x,y, s= 20) # for changing it to scatter plt.scatter() and keep the s which is point size
  plt.plot(a,b,marker='o',markersize=80) 

  for i in range(len(x)):
    plt.annotate("("+str(a[i])+","+str(b[i])+")", (a[i],b[i]), size = ans)
  
  plt.xlabel('Sample no',fontsize = f, fontweight = 'bold')
  plt.ylabel('Variable 2 + Variable 1',fontsize =f, fontweight = 'bold')
  plt.tick_params(labelsize=30)
  plt.savefig('y+x.pdf', bbox_inches = 'tight')


  plt.figure(figsize=(s1,s2))
  #plt.scatter(x,y, s= 20) # for changing it to scatter plt.scatter() and keep the s which is point size
  plt.plot(c,d,marker='o',markersize=80) 

  for i in range(len(x)):
    plt.annotate("("+str(c[i])+","+str(d[i])+")", (c[i],d[i]), size = ans)
  
  plt.xlabel('Sample no',fontsize =f, fontweight = 'bold')
  plt.ylabel('- (Variable 2 + Variable 1)',fontsize = f, fontweight = 'bold')
  plt.tick_params(labelsize=30)
  plt.savefig('-y-x.pdf', bbox_inches = 'tight')
row = 6
col = 10

incrs = 1
decrs = row - incrs

allPairsObjective = findAllpairsObjective(x_t)


#print(len(allPairsObjective))
print("all pair objective")
print(len(allPairsObjective))



x = []
y = []

m,n = 0,1
for j in range(10):
  x.append(x_t[m][j])
  y.append(x_t[n][j])
  

print(x)
print(y)


m = []
n = []

for i in range(10):
  n.append(y[i]-x[i])
  m.append(i)

print(m)
print(n)



a = []
b = []

for i in range(10):
  b.append(y[i]+x[i])
  a.append(i)

print(a)
print(b)


c = []
d = []

for i in range(10):
  d.append(-y[i]-x[i])
  c.append(i)

print(c)
print(d)

drawCurve(x,y,m,n,a,b,c,d)



Output hidden; open in https://colab.research.google.com to view.

In [ ]:
import pandas as pd 
import numpy as np 


# Reading the csv file 
df_new = pd.read_csv('/content/datasetCombined(1).csv') 

# saving xlsx file 
GFG = pd.ExcelWriter('dataCombinedLater.xlsx') 
df_new.to_excel(GFG, index = False) 

GFG.save() 


In [10]:
import seaborn as sn
import matplotlib.pyplot as plt
import pandas

import numpy as np



# load dataset
dataframe = pandas.read_excel('/content/datasetOrginal.xlsx')




asr = dataframe['aspectratio'].tolist()
tArea = dataframe['totalarea'].tolist()
tWlen = dataframe['twirelen'].tolist()
cLkp = dataframe['clkperiod'].tolist()
drc = dataframe['drc'].tolist()
coreU = dataframe['coreutil'].tolist()
twl = dataframe['twl'].tolist()
cpl = dataframe['aspectratio'].tolist()

dis=[]
for i in range(0,len(cpl)):
  if cpl[i] != -100000:
    dis.append(cpl[i])
  if cpl[i] == -100000:
    print('mar')

print(np.mean(dis))




mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
mar
