In [ ]:
!unzip /content/Fuzzy_dataset.csv.zip

Archive:  /content/Fuzzy_dataset.csv.zip
  inflating: Fuzzy_dataset.csv       
   creating: __MACOSX/
  inflating: __MACOSX/._Fuzzy_dataset.csv  


In [ ]:
!unzip /content/Attack_free_dataset2.txt.zip

Archive:  /content/Attack_free_dataset2.txt.zip
  inflating: Attack_free_dataset2.txt  
   creating: __MACOSX/
  inflating: __MACOSX/._Attack_free_dataset2.txt  


In [ ]:
import numpy as np


fileId = open('/content/Attack_free_dataset2.txt', 'r')

detectList = []
counter = 1
graphList = []
ultimateGraphList = [] 
utlimateaDetectionList = []
graphCounter = 0


messageSize = 200

for line in fileId:

  Xpartition = line.split()[0].split(',')
  node = Xpartition[1]
  attackCheck = Xpartition[len(Xpartition)-1]


  graphList.append(node)
  detectList.append(attackCheck)
  

  if len(graphList) == messageSize: 
    ultimateGraphList.append(graphList)
    utlimateaDetectionList.append(detectList)
   

    graphList = []
    detectList = []
   
   

ugl = ultimateGraphList

udl = utlimateaDetectionList

print(len(ugl))
print(len(udl))

print(ugl[0])
print(len(ugl[0]))
print(len(udl[0]))
print(udl[0])
print(udl[3])

19194
19194
['0545', '02b0', '0002', '0153', '0130', '0131', '0140', '0350', '02c0', '0370', '043f', '0440', '04f0', '0316', '018f', '0260', '02a0', '0329', '0545', '02b0', '0430', '04b1', '01f1', '0153', '0002', '00a0', '00a1', '0350', '02c0', '0130', '0131', '0140', '0370', '043f', '0440', '0690', '0316', '018f', '0260', '02a0', '0329', '0545', '02b0', '0002', '0153', '0130', '0131', '0140', '0350', '02c0', '0370', '043f', '0440', '04f0', '0316', '018f', '0260', '02a0', '0329', '0545', '02b0', '0430', '04b1', '01f1', '0153', '0002', '0350', '0370', '043f', '02c0', '0130', '0131', '0140', '0440', '0316', '018f', '0260', '02a0', '0329', '0545', '05f0', '02b0', '0002', '0153', '0130', '0131', '0140', '0350', '02c0', '0370', '043f', '0440', '04f0', '0316', '018f', '0260', '02a0', '0329', '0545', '02b0', '0430', '04b1', '01f1', '0153', '0002', '0350', '0370', '043f', '0130', '0131', '0140', '02c0', '0440', '0316', '018f', '0260', '02a0', '0329', '0545', '02b0', '0002', '0153', '0130', '01

In [ ]:
#Making graph from the 200 sequential of id and store them in a file as Graph adjacent list
from collections import defaultdict
import networkx as nx
import matplotlib.pyplot as plt
import random

gAttackfree=nx.DiGraph()
gAttacked = nx.DiGraph()

lenugl = len(ugl)

fileW = open("FuzzyAttackGraph.txt","w")

counter = 0
gAttackfreeCounter = 0
gAttackedCounter = 0

isNotDone1 = True
isNotDone2 = True 
gAttackfree=nx.DiGraph()
gAttacked = nx.DiGraph()

for i in range(0,lenugl):
  fileW.write("Graph No: "+str(i+1))
  fileW.write("\n")
  dicGraph = defaultdict(list)
  attackFree = 1

  

  for j in range (0, len(ugl[i])-1):
    dicGraph[str(ugl[i][j])].append((ugl[i][j+1]))

  for j in range (0,len(udl[i])):
    if str(udl[i][j]) == 'T': 
      attackFree = 0
      break

  

  
  fileW.write("Attack Free: "+str(attackFree)+"\n")

  for key, val in dicGraph.items():
    fileW.write(str(key) + (" ---> "))
    for m in range(0, len(val)):
      fileW.write(val[m]+"\t")
    fileW.write("\n")


print(counter)
print(gAttackfreeCounter)
print(gAttackedCounter)

fileW.close()

#print(len(list(gAttackfree)))


0
0
0


In [ ]:
#Getting all the features

import networkx as nx
import hashlib
import numpy as np

#Function for tracing the attacked and attackfree graph. Return a list which 
#contation the info that a graph is attacked or attack
def getAttackFreelist(filename):
  attacFreekList = []
  file_ = open(filename, 'r')


  graphCounter = 0
  while True: 
  
    # Get next line from file 
      line = file_.readline() 
  
    # if line is empty 
    # end of file is reached 
      if not line: 
          break
    

    
      graph_number = line[0:5]
    
      if graph_number == "Graph":
      #print(graph_number+str(graphCounter))
        graphCounter += 1
        line = file_.readline()
        attacFreekList.append(line.split())

  
  file_.close()
  print(len(attacFreekList))
  print(attacFreekList)
  return attacFreekList


def getFeatures(filename):

  attackFreeList = getAttackFreelist(filename)
  file_ = open(filename, 'r')

  graphList = []
  ultimate_graphList = []  
  graphCounter = 0
  while True: 
  
    # Get next line from file 
      line = file_.readline() 
  
    # if line is empty 
    # end of file is reached 
      if not line: 
          break
    

    
      graph_number = line[0:5]
    
      if graph_number == "Graph":
      #print(graph_number+str(graphCounter))
        graphCounter += 1
        line = file_.readline()
        line = file_.readline()

        if graphCounter >= 2:
          ultimate_graphList.append(graphList)
          graphList = []


    
      list1 = line.split()
      graphList.append(list1)



  ultimate_graphList.append(graphList)
    
  file_.close()

  list_All_Feature_Set = []
 
  filetowrite = filename[:-4]+"_GraphFeatures.txt"
  file1 = open(filetowrite,'w')

  graphNumber = len(ultimate_graphList)
# Iterating every graph
  for i in range(0,graphNumber):

    G = nx.DiGraph()
    graphEdgeNumber = len(ultimate_graphList[i])
     # defining variable for detecting max pagerank
  #making the graph
    indegree = 0
    outdegree = 0
    
    for j in range(0,graphEdgeNumber):
      vertexConnectionLength = len(ultimate_graphList[i][j])

      for k in range(2,vertexConnectionLength):
      
      
        G.add_edge(ultimate_graphList[i][j][0],ultimate_graphList[i][j][k])
    

    weighted_Feature_Set = nx.pagerank(G)
    
    edge = G.number_of_edges()
    node = G.number_of_nodes()

    
    temp_list = list(weighted_Feature_Set.values())
    median_pagerank_vertices = np.median(temp_list)
    maximum_pagerank_vertex = np.max(temp_list)
    minimum_pagerank_vertex = np.min(temp_list)
    std_pagerank = np.std(temp_list)
    varpagerank = np.var(temp_list)


    if i == 0:
      file1.write("No."+"\t"+"Nodes\t"+"Edges\t"+"MaximumIndegree\t"+"MinimumIndegree\t"+"MaximumOutdegree\t"+
                  "MinimumOutdegree\t"+	
                  "MedianPagerank\t"+"MaximumPagerank\t"+"MininumPagerank\t"+"StdPageRank\t"+
                  "VarPageRank\t"+"State\n")

    file1.write(str(i+1)+"\t")
    counter = 0
    in_deg = []
    out_deg = []
    for key,val in weighted_Feature_Set.items():
      in_deg.append(G.in_degree(key))
      out_deg.append(G.out_degree(key))
    
    maxInd = np.max(in_deg)
    minInd = np.min(in_deg)
    maxOut = np.max(out_deg)
    minOut = np.min(out_deg)
    file1.write(str(node)+"\t") 
    file1.write(str(edge)+"\t")
    file1.write(str(maxInd)+str("\t")+str(minInd)+str("\t"))
    file1.write(str(maxOut)+str("\t")+str(minOut)+str("\t"))
    
    file1.write(str(median_pagerank_vertices)+str("\t")+str(maximum_pagerank_vertex))
    file1.write(str("\t")+str(minimum_pagerank_vertex)+str("\t")+str(std_pagerank)+"\t"+
                str(varpagerank)+"\t"+
                str(attackFreeList[i][2])+"\n")

  


  file1.close()
getFeatures('/content/FuzzyAttackGraph.txt')



19194
[['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Att

In [ ]:
#Applying the GNB and getting the accuracy and confusion matrix

import seaborn as sn
import matplotlib.pyplot as plt
import pandas
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


# load dataset
dataframe = pandas.read_table('/content/FuzzyAttackGraph_GraphFeatures.txt')
data = dataframe.drop("No.", axis=1)
data = data.drop("StdPageRank", axis=1)
data = data.drop("VarPageRank", axis=1)
dataset = data.values



# split into input (X) and output (Y) variables


l = len(ugl)
X = dataset[:,0:]
# print(X.shape)
labels = []
for i in range (0,l):
  if X[i][9] == True:
    labels.append(0)
  else:
    labels.append(1)

features = X[0:l,0:9]


# Split our data
train, test, train_labels, test_labels = train_test_split(features,
                                                            labels,
                                                            test_size=0.33,
                                                            random_state= 898)#

  # Initialize our classifier
gnb = GaussianNB()

  # Train our classifier
model = gnb.fit(train, train_labels)
preds = gnb.predict(test)

print(test_labels.count(1))
print(test_labels.count(0))

  
  # Evaluate accurac
print(accuracy_score(test_labels, preds))

cm = confusion_matrix(test_labels, preds)

cm = cm.T

print(cm)



316
318
1.0
[[318   0]
 [  0 316]]


In [ ]:
# cm = [[18536, 41],
# [ 994 ,7654]]


tp = cm[0][0]
tn = cm[1][1]
fp = cm[0][1]
fn = cm[1][0]

re = tp/(tp+fn)
pr = tp/(tp+fp)
f1 = 2*pr*re/(pr+re)
fpr = fp / (fp+tn)
print("pr.........."+str(pr))
print("re----"+str(re))

print("f1===="+str(f1))
print("fpr====="+ str(fpr))
print((tp+tn)/(tp+tn+fp+fn))

pr..........1.0
re----1.0
f1====1.0
fpr=====0.0
1.0


In [ ]:
72715
180650
0.7177234424644288
[[180319  71188]
 [   331   1527]]
5


41059
85624
0.702556775573676
[[84780 36837]
 [  844  4222]]
10

4334
8335
0.9970005525297971
[[8335   38]
 [   0 4296]]
 100


2180
4155
0.9984214680347278
[[4148    3]
 [   7 2177]]
 200


944
1590
0.9952644041041832
[[1582    4]
 [   8  940]]
 500


 503
764
0.9992107340173638
[[764   1]
 [  0 502]]
 1k


316
318
1.0
[[318   0]
 [  0 316]]
2k

 184
70
1.0
[[ 70   0]
 [  0 184]]
 5k


93
34
1.0
[[34  0]
 [ 0 93]]
 10k