In [ ]:
#Library initialization
import numpy as np



#Parameter initialization
T = 120000 #Time for simulations
Nc = 30 #Number of cluster size
t =  300 # time to capture by the rnn

sizeClusters = 80  #Number of excitory neurons per clusters
stdpdelay = 800    #Stdpdelay


Rex = 18 #rate of externald drive

dt = 0.1            #Minimum time steps


Excitory_neurons = 2400
Inhibitory_neurons = int(.25*(Excitory_neurons))
Init_ext2ext_wt = 2.83 #; % initial ee strength
Init_ext2inh_wt = 62.87 #; % initial ei strength
Init_inh2ext_wt =  1.96#; %ie strength (not plastic)
Init_inh2inh_wt =  20.91#; %ii strength (not plastic)
p = 0.2 #;




#stimulus to the rnn
duty_on = t/Nc #on period of the duty cycle
duty_cycle = 1.5*duty_on #Total duty cycle
time_stimulation = T/duty_cycle #time for stimulation for stim function



stim = np.zeros((int(time_stimulation),4))



#fileW = open("stim.txt","w")

for i in range(0,int(time_stimulation)):
    stim[i][0] = i%Nc + 1
    stim[i][1] = 1+duty_cycle*i
    stim[i][2] = duty_on+duty_cycle*i
    stim[i][3] = Rex












In [ ]:
#weight declaration
    
Total_neurons=Excitory_neurons+Inhibitory_neurons

weights = np.zeros((Total_neurons,Total_neurons))
weights[0:Excitory_neurons,0:Excitory_neurons] = Init_ext2ext_wt
weights[0:Excitory_neurons,Excitory_neurons:Total_neurons] = Init_inh2ext_wt
weights[0+Excitory_neurons:Total_neurons,0:Excitory_neurons] = Init_ext2inh_wt
weights[0+Excitory_neurons:Total_neurons,Excitory_neurons:Total_neurons] = Init_inh2inh_wt



weights = weights*(np.random.rand(Total_neurons,Total_neurons) < p)

for cc in range(Total_neurons):
		weights[cc][cc] = 0





e_cluster = np.zeros((Nc,sizeClusters))
for pp in range(Nc):
    a=int((Excitory_neurons*pp)/Nc)
    b=int((Excitory_neurons*(pp+1))/Nc)
    e_cluster[pp][0:sizeClusters]=[i for i in range(a,b)]

    

print(e_cluster)



# print(list(weights.flatten()).count(0))
# print(Total_neurons**2*.8)
filew = open("stim.txt","w")

for i in range(Nc):
  for j in range(sizeClusters):
    filew.write(str(e_cluster[i][j])+"\t")
  filew.write("\n")

[[0.000e+00 1.000e+00 2.000e+00 ... 7.700e+01 7.800e+01 7.900e+01]
 [8.000e+01 8.100e+01 8.200e+01 ... 1.570e+02 1.580e+02 1.590e+02]
 [1.600e+02 1.610e+02 1.620e+02 ... 2.370e+02 2.380e+02 2.390e+02]
 ...
 [2.160e+03 2.161e+03 2.162e+03 ... 2.237e+03 2.238e+03 2.239e+03]
 [2.240e+03 2.241e+03 2.242e+03 ... 2.317e+03 2.318e+03 2.319e+03]
 [2.320e+03 2.321e+03 2.322e+03 ... 2.397e+03 2.398e+03 2.399e+03]]
