In [ ]:
!unzip /content/mergeAttackFreeImperstion.zip

Archive:  /content/mergeAttackFreeImperstion.zip
  inflating: mergeAttackFreeImperstion.txt  


In [ ]:
import numpy as np

attackFreeArray = []
file = open('/content/mergeAttackFreeImperstion.txt', 'r')
timeList = []
counter = 1
graphList = []
ultimateGraphList = [] 
utlimateTimeList = []
graphCounter = 0
noOfMessages = 2000
for line in file:
  node = line.split()[0]

  if node == 'ID':
    continue

  graphList.append(node)
  timeList.append(counter)

  if len(graphList) == noOfMessages:  #no of messages
    ultimateGraphList.append(graphList)
    utlimateTimeList.append(timeList)

    graphList = []
    timeList = []

   
  
  counter +=1

ugl = ultimateGraphList
utl = utlimateTimeList


print(len(ugl))

print(ugl[0])
print(len(ugl[0]))
print(len(utlimateTimeList[0]))
print(utlimateTimeList[0])
print(utlimateTimeList[3])

2186
['04b0', '05a0', '05a0', '02a0', '0260', '0080', '0081', '0165', '018f', '02b0', '0153', '0220', '0316', '0329', '0545', '043f', '0370', '0440', '0164', '04b1', '0316', '018f', '0260', '0080', '0081', '0165', '02a0', '02b0', '0329', '0153', '01f1', '0220', '0382', '0350', '04f2', '0545', '00a0', '00a1', '0370', '043f', '0440', '04f0', '05a2', '04f1', '05a2', '051a', '0690', '04b0', '0316', '018f', '0080', '0081', '0153', '0153', '0165', '0153', '0220', '0260', '02a0', '02b0', '0329', '0545', '043f', '0370', '0440', '0587', '05a0', '04b1', '0164', '0316', '0260', '02a0', '0080', '0081', '0164', '0165', '0153', '018f', '01f1', '0220', '02b0', '02c0', '0329', '0350', '0370', '0120', '0382', '0164', '043f', '0440', '04f2', '0517', '04f0', '0545', '05a2', '04b0', '0316', '0260', '018f', '0080', '0081', '0165', '0153', '01f1', '0220', '01f1', '02a0', '02b0', '0329', '0545', '043f', '0370', '0440', '0510', '04b1', '0164', '05e4', '0165', '02b0', '0080', '0081', '0153', '018f', '01f1', '0

In [ ]:
#Making graph from the 200 sequential of id and store them in a file as Graph adjacent list
from collections import defaultdict

import networkx as nx
import matplotlib.pyplot as plt
import random

gAttackfree=nx.DiGraph()
gAttacked = nx.DiGraph()

lenugl = len(ugl)

fileW = open("AttackFreeGraphImpersion.txt","w")

counter = 0
gAttackfreeCounter = 0
gAttackedCounter = 0

isNotDone1 = True
isNotDone2 = True 
gAttackfree=nx.DiGraph()
gAttacked = nx.DiGraph()

for i in range(0,lenugl):
  fileW.write("Graph No: "+str(i+1))
  fileW.write("\n")
  dicGraph = defaultdict(list)
  attackFree = True

  

  for j in range (0, len(ugl[i])-1):
    dicGraph[str(ugl[i][j])].append((ugl[i][j+1]))

  for j in range (0,len(ugl[i])):
    if str(ugl[i][j]) == '0164' and utl[i][j] >= 527250 and utl[i][j] <= 659990: 
      attackFree = False
      break
    


  

  
  fileW.write("Attack Free: "+str(attackFree)+"\n")

  for key, val in dicGraph.items():
    fileW.write(str(key) + (" ---> "))
    for m in range(0, len(val)):
      fileW.write(val[m]+"\t")
    fileW.write("\n")


print(counter)
print(gAttackfreeCounter)
print(gAttackedCounter)

fileW.close()

#print(len(list(gAttackfree)))


0
0
0


In [ ]:
#Getting all the features

import networkx as nx
import hashlib
import numpy as np

#Function for tracing the attacked and attackfree graph. Return a list which 
#contation the info that a graph is attacked or attack
def getAttackFreelist(filename):
  attacFreekList = []
  file_ = open(filename, 'r')


  graphCounter = 0
  while True: 
  
    # Get next line from file 
      line = file_.readline() 
  
    # if line is empty 
    # end of file is reached 
      if not line: 
          break
    

    
      graph_number = line[0:5]
    
      if graph_number == "Graph":
      #print(graph_number+str(graphCounter))
        graphCounter += 1
        line = file_.readline()
        attacFreekList.append(line.split())

  
  file_.close()
  print(len(attacFreekList))
  print(attacFreekList)
  return attacFreekList


def getFeatures(filename):

  attackFreeList = getAttackFreelist(filename)
  file_ = open(filename, 'r')

  graphList = []
  ultimate_graphList = []  
  graphCounter = 0
  while True: 
  
    # Get next line from file 
      line = file_.readline() 
  
    # if line is empty 
    # end of file is reached 
      if not line: 
          break
    

    
      graph_number = line[0:5]
    
      if graph_number == "Graph":
      #print(graph_number+str(graphCounter))
        graphCounter += 1
        line = file_.readline()
        line = file_.readline()

        if graphCounter >= 2:
          ultimate_graphList.append(graphList)
          graphList = []


    
      list1 = line.split()
      graphList.append(list1)



  ultimate_graphList.append(graphList)
    
  file_.close()

  list_All_Feature_Set = []
 


  graphNumber = len(ultimate_graphList)
# Iterating every graph
  allFeatureList = []
  allLabelList = []
  for i in range(0,graphNumber):

    G = nx.DiGraph()
    
    graphEdgeNumber = len(ultimate_graphList[i])
     # defining variable for detecting max pagerank
  #making the graph
    indegree = 0
    outdegree = 0
    
    for j in range(0,graphEdgeNumber):
      vertexConnectionLength = len(ultimate_graphList[i][j])

      for k in range(2,vertexConnectionLength):
      
      
        G.add_edge(ultimate_graphList[i][j][0],ultimate_graphList[i][j][k])
    

    weighted_Feature_Set = nx.pagerank(G)
    
    edge = G.number_of_edges()
    node = G.number_of_nodes()

    
    temp_list = list(weighted_Feature_Set.values())
    median_pagerank_vertices = np.median(temp_list)
    maximum_pagerank_vertex = np.max(temp_list)
    minimum_pagerank_vertex = np.min(temp_list)
    std_pagerank = np.std(temp_list)
    varpagerank = np.var(temp_list)



    counter = 0
    in_deg = []
    out_deg = []
    for key,val in weighted_Feature_Set.items():
      in_deg.append(G.in_degree(key))
      out_deg.append(G.out_degree(key))
    
    maxInd = np.max(in_deg)
    minInd = np.min(in_deg)
    maxOut = np.max(out_deg)
    minOut = np.min(out_deg)

    allFeatureList.append([node,edge,maxInd,minInd,maxOut,minOut,median_pagerank_vertices,maximum_pagerank_vertex,
                            minimum_pagerank_vertex,std_pagerank,varpagerank])
    
    if attackFreeList[i][2] == 'False':
      allLabelList.append(1)
      for p in range(30):
        allFeatureList.append([node,edge,maxInd,minInd,maxOut,minOut,median_pagerank_vertices,maximum_pagerank_vertex,
                            minimum_pagerank_vertex,std_pagerank,varpagerank])
        allLabelList.append(1)

    else:
      allLabelList.append(0)
    
  return allFeatureList,allLabelList


  


  
allFeatureList,allLabelList = getFeatures('/content/AttackFreeGraphImpersion.txt')

print(len(allFeatureList))
print(allLabelList.count(1))



2186
[['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack', 'Free:', 'True'], ['Attack

In [ ]:
import torch
import numpy as np
import numpy as np 
from scipy.sparse import csr_matrix
uList = []
vList = []
aList = []

for i in range(len(allLabelList)-1):
  uList.append(i)
  vList.append(i+1)
  aList.append(1)


aList = csr_matrix((np.array(aList), (np.array(uList), np.array(vList))),  
                          shape = (len(allLabelList), len(allLabelList))).toarray() 






print('asjksjf')


nList = np.array(allFeatureList)
aList = np.array(aList)

lList = np.array(allLabelList)



aList = torch.from_numpy(aList)
nList = torch.from_numpy(nList)
lList = torch.from_numpy(lList)


print(len(nList))

print(len(aList))

print(len(lList))


print(nList)

print(aList)

print(lList)





# print(idx_train)
# print(idx_val)
# print(idx_test)


asjksjf
4196
4196
4196
tensor([[4.4000e+01, 3.1600e+02, 2.6000e+01,  ..., 5.4347e-03, 1.4907e-02,
         2.2222e-04],
        [4.5000e+01, 3.4200e+02, 3.2000e+01,  ..., 4.1759e-03, 1.6145e-02,
         2.6067e-04],
        [4.5000e+01, 3.3800e+02, 2.9000e+01,  ..., 4.4643e-03, 1.6005e-02,
         2.5615e-04],
        ...,
        [2.7000e+01, 9.1000e+01, 8.0000e+00,  ..., 1.0066e-02, 1.9679e-02,
         3.8726e-04],
        [2.7000e+01, 1.0600e+02, 9.0000e+00,  ..., 8.5040e-03, 1.6964e-02,
         2.8778e-04],
        [2.7000e+01, 7.0000e+01, 7.0000e+00,  ..., 1.4501e-02, 1.9989e-02,
         3.9956e-04]], dtype=torch.float64)
tensor([[0, 1, 0,  ..., 0, 0, 0],
        [0, 0, 1,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 1, 0],
        [0, 0, 0,  ..., 0, 0, 1],
        [0, 0, 0,  ..., 0, 0, 0]])
tensor([0, 0, 0,  ..., 0, 0, 0])


In [ ]:
import math

import torch
import numpy as np


import time
import argparse
import numpy as np

import torch
import torch.nn.functional as F
import torch.optim as optim
from sklearn.metrics import confusion_matrix

from torch.nn.parameter import Parameter
from torch.nn.modules.module import Module
import torch.nn as nn
import torch.nn.functional as F


class GraphConvolution(Module):

    def __init__(self, in_features, out_features, bias=True):
        super(GraphConvolution, self).__init__()
        
        # print(in_features)
        # print(out_features)
        self.in_features = in_features
        self.out_features = out_features
        self.weight = Parameter(torch.DoubleTensor(in_features, out_features))
        if bias:
            self.bias = Parameter(torch.DoubleTensor(out_features))
        else:
            self.register_parameter('bias', None)
        self.reset_parameters()
    
    def reset_parameters(self):
        stdv = 1. / math.sqrt(self.weight.size(1))
        self.weight.data.uniform_(-stdv, stdv)
        if self.bias is not None:
            self.bias.data.uniform_(-stdv, stdv)

    def forward(self, input, adj):
        support = torch.matmul(input, self.weight)
        output = torch.matmul(adj, support)
        if self.bias is not None:
            return output + self.bias
        else:
            return output

    def __repr__(self):
        return self.__class__.__name__ + ' (' \
               + str(self.in_features) + ' -> ' \
               + str(self.out_features) + ')'

class GCN(nn.Module):
    def __init__(self, nfeat, nhid, nclass, dropout):
        super(GCN, self).__init__()

        self.gc1 = GraphConvolution(nfeat, nhid)
        self.gc2 = GraphConvolution(nhid, nclass)
        self.dropout = dropout

    def forward(self, x, adj):
        x = F.relu(self.gc1(x, adj))
        x = F.dropout(x, self.dropout, training=self.training)
        x = self.gc2(x, adj)
        #print(F.log_softmax(x, dim=1))
        return F.log_softmax(x, dim=1)


seed = 42
epochs = 10
lr = 0.01
weight_decay = 5e-4
hidden = 16
dropout =0.5
np.random.seed(seed)




adj, features, labels = aList, nList, lList

#adj, features, labels = aList[, nList, lList

f = int(len(allLabelList)*.15)
g = int(len(allLabelList)*.70)
h = int(len(allLabelList)*.15)

print(f)
print(g)
print(h)

idx_train = torch.LongTensor(range(f,f+g))
idx_test = torch.LongTensor(range(f))
idx_val = torch.LongTensor(range(f+g,f+g+h))

# Model and optimizer
print(features.shape)
model = GCN(nfeat=features.shape[1],
            nhid=hidden,
            nclass=labels.max().item() + 1,
            dropout=dropout)
#print(model)
optimizer = optim.Adam(model.parameters(),
                       lr=lr, weight_decay=weight_decay)


fastmode = False


def accuracy(output, labels, t = 0):
    preds = output.max(1)[1].type_as(labels)
    if t == 1:
      print(np.array(confusion_matrix(list(labels),list(preds))).T)
      print(len(labels))
    correct = preds.eq(labels).double()
    correct = correct.sum()
    return correct / len(labels)

def train(epoch):
    t = time.time()
    model.train()
    optimizer.zero_grad()
    #print(features.shape)
    output = model(features, adj)
    # print(output.shape)
    # print(output[idx_train].shape)
    # print(labels[idx_train].shape)
    loss_train = F.nll_loss(output[idx_train], labels[idx_train])
    acc_train = accuracy(output[idx_train], labels[idx_train])
    loss_train.backward()
    optimizer.step()

    if not fastmode:
        # Evaluate validation set performance separately,
        # deactivates dropout during validation run.
        model.eval()
        #print(features.shape)
        #print(model)
        output = model(features, adj)

    loss_val = F.nll_loss(output[idx_val], labels[idx_val])
    acc_val = accuracy(output[idx_val], labels[idx_val])
    print('Epoch: {:04d}'.format(epoch+1),
          'loss_train: {:.4f}'.format(loss_train.item()),
          'acc_train: {:.4f}'.format(acc_train.item()),
          'loss_val: {:.4f}'.format(loss_val.item()),
          'acc_val: {:.4f}'.format(acc_val.item()),
          'time: {:.4f}s'.format(time.time() - t))


def test(t=0):
    model.eval()
    output = model(features, adj)
    loss_test = F.nll_loss(output[idx_test], labels[idx_test])
    
    acc_test= accuracy(output[idx_test], labels[idx_test],t)
    
    print("Test set results:",
          "loss= {:.4f}".format(loss_test.item()),
          "accuracy= {:.4f}".format(acc_test.item()))
    


# Train model
t_total = time.time()
for epoch in range(epochs):
    train(epoch)
print("Optimization Finished!")
print("Total time elapsed: {:.4f}s".format(time.time() - t_total))

# Testing
t_total = time.time()
test(1)
print("Total time elapsed: {:.4f}s".format(time.time() - t_total))










6267
29249
6267
torch.Size([41785, 11])


RuntimeError: ignored

In [ ]:
# cm = [[1612 ,  10],
#  [   5  ,793]]


tp = cm[0][0]
tn = cm[1][1]
fp = cm[0][1]
fn = cm[1][0]

re = tp/(tp+fn)
pr = tp/(tp+fp)
f1 = 2*pr*re/(pr+re)
fpr = fp / (fp+tn)
print("pr.........."+str(pr))
print("re----"+str(re))

print("f1===="+str(f1))
print("fpr====="+ str(fpr))
print((tp+tn)/(tp+tn+fp+fn))

pr..........0.98989898989899
re----0.9932432432432432
f1====0.9915682967959528
fpr=====0.009708737864077669
0.9917355371900827


In [ ]:
71002
170939
0.991287131986724
[[170760   1929]
 [   179  69073]]
 5

35791
85180
0.9906010531449686
[[84065    22]
 [ 1115 35769]]
 10


3659
8438
0.9962800694387038
[[8424   31]
 [  14 3628]]
100


1832
4217
0.993387336749876
[[4197   20]
 [  20 1812]]

803
1617
0.993801652892562
[[1612   10]
 [   5  793]]
 500



 464
746
0.9917355371900827
[[743   7]
 [  3 457]]
 1000



 309
296
0.9917355371900827
[[294   3]
 [  2 306]]
 2k

 175
67
1.0
[[ 67   0]
 [  0 175]]
 5k


 88
33
1.0
[[33  0]
 [ 0 88]]
 10k

In [ ]:
cm =[ [[170760 ,  1929],
 [179 , 69073]],

 [[84065   , 22],
 [ 1115, 35769]],

[[8424 ,  31],
 [  14, 3628]],

 [[4197 ,  20],
 [  20 ,1812]],

 [[1612  , 10],
 [   5  ,793]],

[[743 ,  7],
 [  3 ,457]],


 [[ 67 ,  0],
 [  0 ,175]],

 [[33,  0],
 [ 0, 88]]
]

for i in range(len(cm)):

  tp = cm[i][0][0]
  tn = cm[i][1][1]
  fp = cm[i][0][1]
  fn = cm[i][1][0]

  re = tp/(tp+fn)
  pr = tp/(tp+fp)
  f1 = 2*pr*re/(pr+re)
  fpr = fp / (fp+tn)


  mcc = (tp*tn-fp*fn)/((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn))**.5

  fdr = fp/(fp+tp)

  # print("pr.........."+str(pr))
  # print("re----"+str(re))

  # print("f1===="+str(f1))
  # print("fpr====="+ str(fpr))
  print("mcccccc--------->" +str(mcc))
  #print("fdr======="+str(fdr))
  # print((tp+tn)/(tp+tn+fp+fn))

mcccccc--------->0.9789880325873227
mcccccc--------->0.9778659028555149
mcccccc--------->0.991178167512607
mcccccc--------->0.9843402613459972
mcccccc--------->0.9860106010676708
mcccccc--------->0.9825172905181248
mcccccc--------->1.0
mcccccc--------->1.0


In [ ]:
import pandas as pd

square_node_data = pd.DataFrame(
    {"x": [1, 2, 3, 4], "y": [-0.2, 0.3, 0.0, -0.5]}, index=["a", "b", "c", "d"]
)
square_node_data

x    y
a  1 -0.2
b  2  0.3
c  3  0.0
d  4 -0.5

      Nodes  Edges  ...  MaximumPagerank  MininumPagerank
No.                 ...                                  
1        27    112  ...         0.215139         0.011104
2        25     75  ...         0.359649         0.018228
3        25     88  ...         0.285778         0.015716
4        27     97  ...         0.276848         0.014271
5        27    137  ...         0.173902         0.013195
...     ...    ...  ...              ...              ...
1828     26     70  ...         0.077329         0.013768
1829     26     73  ...         0.073358         0.011842
1830     26     78  ...         0.067820         0.011954
1831     26     85  ...         0.071132         0.009662
1832     26     76  ...         0.086512         0.008505

[1832 rows x 9 columns]
StellarGraph: Undirected multigraph
 Nodes: 1832, Edges: 0

 Node types:
  default: [1832]
    Features: float32 vector, length 9
    Edge types: none

 Edge types:
