In [20]:
import seaborn as sn
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd


# load dataset
dataframe = pandas.read_table('/content/completeallwithNode.txt')
data1 = dataframe.drop("No.", axis=1)
data2 = data1.drop("State", axis =1)
dataset = dataframe.values



# split into input (X) and output (Y) variables

 
l = 79854
X = dataset[0:l,1:]
# Y = dataset[100:200, 1:10]
# print(X)
# print(X.shape)
labels = []
for i in range (0,l):
  if X[i][9] == 'T':
    labels.append(0)
  else:
    labels.append(1)

features = X[0:l,0:9]

X_train, X_test, Y_train, Y_test = train_test_split(features, labels, test_size=0.33)

values = pd.DataFrame(X_train).memory_usage(index = False) 

print(values)
sum = 0

# for key,val in values.items():
#   #print(key)
#   sum = sum+val
# print(sum/(1024*1024))
# print(len(features))
# print(len(features[0]))
# print(features)
# print(labels)

0    428016
1    428016
2    428016
3    428016
4    428016
5    428016
6    428016
7    428016
8    428016
dtype: int64
3.6736907958984375


In [29]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Embedding, LSTM, GRU, Input
from keras.layers import Conv2D, MaxPooling2D, Conv1D,MaxPooling1D
from keras import backend as K
from keras.preprocessing.text import Tokenizer, hashing_trick
from keras.preprocessing.sequence import pad_sequences
import tensorflow as tf
from keras.utils import to_categorical
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

features = np.array(features,dtype='float64')
labels = np.array(labels, dtype ='float64')

# min_max_scaler = MinMaxScaler()
# X = min_max_scaler.fit_transform(features)

X_train, X_test, Y_train, Y_test = train_test_split(features, labels, test_size=0.33)

model = Sequential([ Dense(32, activation='relu', input_shape=(9,)), Dense(32, activation='relu'), Dense(1, activation='sigmoid'),])
# compile the keras model
model.compile(loss = 'binary_crossentropy', optimizer='adam',metrics = ['accuracy'])
model.fit( np.array(X_train),#.reshape((train_X.shape[0], train_X.shape[1],1)), 
           np.array(Y_train),
           epochs = 10, 
           batch_size=32, 
           verbose = 1
          #, validation_data=(np.array(X_test), np.array(Y_test))
           )

_, accuracy = model.evaluate(X_test, Y_test)
print('Accuracy: %.2f' % (accuracy*100))

yhat_classes = model.predict_classes(X_test, verbose=0)

# testy = Y_test
# # accuracy: (tp + tn) / (p + n)
# accuracy = accuracy_score(testy, yhat_classes)
# print('Accuracy: %f' % accuracy)
# # precision tp / (tp + fp)
# precision = precision_score(testy, yhat_classes)
# print('Precision: %f' % precision)
# # recall: tp / (tp + fn)
# recall = recall_score(testy, yhat_classes)
# print('Recall: %f' % recall)
# # f1: 2 tp / (2 tp + fp + fn)
# f1 = f1_score(testy, yhat_classes)
# print('F1 score: %f' % f1)

print(model.summary())


Epoch 1/10
1672/1672 [==============================] - 2s 1ms/step - loss: 0.1336 - accuracy: 0.9686
Epoch 2/10
1672/1672 [==============================] - 2s 1ms/step - loss: 0.0861 - accuracy: 0.9812
Epoch 3/10
1672/1672 [==============================] - 2s 1ms/step - loss: 0.0834 - accuracy: 0.9820
Epoch 4/10
1672/1672 [==============================] - 2s 1ms/step - loss: 0.0821 - accuracy: 0.9822
Epoch 5/10
1672/1672 [==============================] - 2s 1ms/step - loss: 0.0813 - accuracy: 0.9823
Epoch 6/10
1672/1672 [==============================] - 2s 1ms/step - loss: 0.0805 - accuracy: 0.9824
Epoch 7/10
1672/1672 [==============================] - 2s 1ms/step - loss: 0.0801 - accuracy: 0.9824
Epoch 8/10
1672/1672 [==============================] - 2s 1ms/step - loss: 0.0796 - accuracy: 0.9825
Epoch 9/10
1672/1672 [==============================] - 2s 1ms/step - loss: 0.0795 - accuracy: 0.9826
Epoch 10/10
824/824 [==============================] - 1s 851us/step - loss: 0.084

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
# Split our data
train, test, train_labels, test_labels = train_test_split(features,
                                                          labels,
                                                          test_size=0.33,
                                                          random_state=42)

# Initialize our classifier
lr =  LogisticRegression()
svc = SVC()
kc = KNeighborsClassifier()
dtc = DecisionTreeClassifier()
mlp = MLPClassifier()


# Train our classifier
lr.fit(train, train_labels)
svc.fit(train, train_labels)
kc.fit(train, train_labels)
dtc.fit(train, train_labels)
mlp.fit(train, train_labels)

print("Logistic Regrssion")
preds = lr.predict(test)
print(preds)
print(classification_report(test_labels,preds))

print("SVM")
preds = svc.predict(test)
print(preds)
print(classification_report(test_labels,preds))

print("KC")
preds = kc.predict(test)
print(preds)
print(classification_report(test_labels,preds))

print("DTC")
preds = dtc.predict(test)
print(preds)
print(classification_report(test_labels,preds))


print("MLP")
preds = mlp.predict(test)
print(preds)
print(classification_report(test_labels,preds))
# Evaluate accuracy



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Logistic Regrssion
[0 0 1 ... 0 1 0]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     18142
           1       1.00      0.95      0.97      8210

    accuracy                           0.98     26352
   macro avg       0.99      0.97      0.98     26352
weighted avg       0.98      0.98      0.98     26352

SVM
[0 0 1 ... 0 1 0]
              precision    recall  f1-score   support

           0       0.97      1.00      0.99     18142
           1       1.00      0.94      0.97      8210

    accuracy                           0.98     26352
   macro avg       0.99      0.97      0.98     26352
weighted avg       0.98      0.98      0.98     26352

KC
[0 0 1 ... 0 1 0]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     18142
           1       1.00      0.95      0.97      8210

    accuracy                           0.98     26352
   macro avg       0.99      0.97      0.98     