In [1]:
!unzip /content/170907_impersonation.txt.zip

Archive:  /content/170907_impersonation.txt.zip
  inflating: 170907_impersonation.txt  
   creating: __MACOSX/
  inflating: __MACOSX/._170907_impersonation.txt  


In [2]:
!unzip /content/mergeAttackFreeImperstion.zip

Archive:  /content/mergeAttackFreeImperstion.zip
  inflating: mergeAttackFreeImperstion.txt  


In [3]:
import numpy as np

attackFreeArray = []
file = open('/content/mergeAttackFreeImperstion.txt', 'r')
timeList = []
counter = 1
graphList = []
ultimateGraphList = [] 
utlimateTimeList = []
graphCounter = 0
noOfMessages = 200
for line in file:
  node = line.split()[0]

  if node == 'ID':
    continue

  graphList.append(node)
  timeList.append(counter)

  if len(graphList) == noOfMessages:  #no of messages
    ultimateGraphList.append(graphList)
    utlimateTimeList.append(timeList)

    graphList = []
    timeList = []
   
  
  counter +=1

ugl = ultimateGraphList
utl = utlimateTimeList


print(len(ugl))

print(ugl[0])
print(len(ugl[0]))
print(len(utlimateTimeList[0]))
print(utlimateTimeList[0])
print(utlimateTimeList[3])

21865
['04b0', '05a0', '05a0', '02a0', '0260', '0080', '0081', '0165', '018f', '02b0', '0153', '0220', '0316', '0329', '0545', '043f', '0370', '0440', '0164', '04b1', '0316', '018f', '0260', '0080', '0081', '0165', '02a0', '02b0', '0329', '0153', '01f1', '0220', '0382', '0350', '04f2', '0545', '00a0', '00a1', '0370', '043f', '0440', '04f0', '05a2', '04f1', '05a2', '051a', '0690', '04b0', '0316', '018f', '0080', '0081', '0153', '0153', '0165', '0153', '0220', '0260', '02a0', '02b0', '0329', '0545', '043f', '0370', '0440', '0587', '05a0', '04b1', '0164', '0316', '0260', '02a0', '0080', '0081', '0164', '0165', '0153', '018f', '01f1', '0220', '02b0', '02c0', '0329', '0350', '0370', '0120', '0382', '0164', '043f', '0440', '04f2', '0517', '04f0', '0545', '05a2', '04b0', '0316', '0260', '018f', '0080', '0081', '0165', '0153', '01f1', '0220', '01f1', '02a0', '02b0', '0329', '0545', '043f', '0370', '0440', '0510', '04b1', '0164', '05e4', '0165', '02b0', '0080', '0081', '0153', '018f', '01f1', '

In [4]:
#Making graph from the 200 sequential of id and store them in a file as Graph adjacent list
from collections import defaultdict
import networkx as nx
import matplotlib.pyplot as plt
import random

gAttackfree=nx.DiGraph()
gAttacked = nx.DiGraph()

lenugl = len(ugl)

fileW = open("AttackFreeGraphImpersion.txt","w")

counter = 0
gAttackfreeCounter = 0
gAttackedCounter = 0

isNotDone1 = True
isNotDone2 = True 
gAttackfree=nx.DiGraph()
gAttacked = nx.DiGraph()

for i in range(0,lenugl):
  fileW.write("Graph No: "+str(i+1))
  fileW.write("\n")
  dicGraph = defaultdict(list)
  attackFree = 1

  

  for j in range (0, len(ugl[i])-1):
    dicGraph[str(ugl[i][j])].append((ugl[i][j+1]))

  for j in range (0,len(ugl[i])):
    if str(ugl[i][j]) == '0164' and utl[i][j] >= 527250 and utl[i][j] <= 659990: 
      attackFree = 0
      break
    


  

  
  fileW.write("Attack Free: "+str(attackFree)+"\n")

  for key, val in dicGraph.items():
    fileW.write(str(key) + (" ---> "))
    for m in range(0, len(val)):
      fileW.write(val[m]+"\t")
    fileW.write("\n")


print(counter)
print(gAttackfreeCounter)
print(gAttackedCounter)

fileW.close()

#print(len(list(gAttackfree)))


0
0
0


In [5]:
#Getting all the features

import networkx as nx
import hashlib
import numpy as np

#Function for tracing the attacked and attackfree graph. Return a list which 
#contation the info that a graph is attacked or attack
def getAttackFreelist(filename):
  attacFreekList = []
  file_ = open(filename, 'r')


  graphCounter = 0
  while True: 
  
    # Get next line from file 
      line = file_.readline() 
  
    # if line is empty 
    # end of file is reached 
      if not line: 
          break
    

    
      graph_number = line[0:5]
    
      if graph_number == "Graph":
      #print(graph_number+str(graphCounter))
        graphCounter += 1
        line = file_.readline()
        attacFreekList.append(line.split())

  
  file_.close()
  print(len(attacFreekList))
  print(attacFreekList)
  return attacFreekList


def getFeatures(filename):

  attackFreeList = getAttackFreelist(filename)
  file_ = open(filename, 'r')

  graphList = []
  ultimate_graphList = []  
  graphCounter = 0
  while True: 
  
    # Get next line from file 
      line = file_.readline() 
  
    # if line is empty 
    # end of file is reached 
      if not line: 
          break
    

    
      graph_number = line[0:5]
    
      if graph_number == "Graph":
      #print(graph_number+str(graphCounter))
        graphCounter += 1
        line = file_.readline()
        line = file_.readline()

        if graphCounter >= 2:
          ultimate_graphList.append(graphList)
          graphList = []


    
      list1 = line.split()
      graphList.append(list1)



  ultimate_graphList.append(graphList)
    
  file_.close()

  list_All_Feature_Set = []
 
  filetowrite = filename[:-4]+"_GraphFeatures.txt"
  file1 = open(filetowrite,'w')

  graphNumber = len(ultimate_graphList)
# Iterating every graph
  for i in range(0,graphNumber):

    G = nx.DiGraph()
    graphEdgeNumber = len(ultimate_graphList[i])
     # defining variable for detecting max pagerank
  #making the graph
    indegree = 0
    outdegree = 0
    
    for j in range(0,graphEdgeNumber):
      vertexConnectionLength = len(ultimate_graphList[i][j])

      for k in range(2,vertexConnectionLength):
      
      
        G.add_edge(ultimate_graphList[i][j][0],ultimate_graphList[i][j][k])
    

    weighted_Feature_Set = nx.pagerank(G)
    
    edge = G.number_of_edges()
    node = G.number_of_nodes()

    
    temp_list = list(weighted_Feature_Set.values())
    median_pagerank_vertices = np.median(temp_list)
    maximum_pagerank_vertex = np.max(temp_list)
    minimum_pagerank_vertex = np.min(temp_list)
    std_pagerank = np.std(temp_list)
    varpagerank = np.var(temp_list)


    if i == 0:
      file1.write("No."+"\t"+"Nodes\t"+"Edges\t"+"MaximumIndegree\t"+"MinimumIndegree\t"+"MaximumOutdegree\t"+
                  "MinimumOutdegree\t"+	
                  "MedianPagerank\t"+"MaximumPagerank\t"+"MininumPagerank\t"+"StdPageRank\t"+
                  "VarPageRank\t"+"State\n")

    file1.write(str(i+1)+"\t")
    counter = 0
    in_deg = []
    out_deg = []
    for key,val in weighted_Feature_Set.items():
      in_deg.append(G.in_degree(key))
      out_deg.append(G.out_degree(key))
    
    maxInd = np.max(in_deg)
    minInd = np.min(in_deg)
    maxOut = np.max(out_deg)
    minOut = np.min(out_deg)
    file1.write(str(node)+"\t") 
    file1.write(str(edge)+"\t")
    file1.write(str(maxInd)+str("\t")+str(minInd)+str("\t"))
    file1.write(str(maxOut)+str("\t")+str(minOut)+str("\t"))
    
    file1.write(str(median_pagerank_vertices)+str("\t")+str(maximum_pagerank_vertex))
    file1.write(str("\t")+str(minimum_pagerank_vertex)+str("\t")+str(std_pagerank)+"\t"+
                str(varpagerank)+"\t"+
                str(attackFreeList[i][2])+"\n")

  


  file1.close()
getFeatures('/content/AttackFreeGraphImpersion.txt')



21865
[['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Att

In [ ]:
#Applying the GNB and getting the accuracy and confusion matrix

import seaborn as sn
import matplotlib.pyplot as plt
import pandas
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


# load dataset
dataframe = pandas.read_table('/content/AttackFreeGraphImpersion_GraphFeatures.txt')
data = dataframe.drop("No.", axis=1)
data = data.drop("StdPageRank", axis=1)
data = data.drop("VarPageRank", axis=1)
dataset = data.values



# split into input (X) and output (Y) variables


l = len(ugl)
X = dataset[:,0:]
# print(X.shape)
labels = []
for i in range (0,l):
  if X[i][9] == True:
    labels.append(0)
  else:
    labels.append(1)

features = X[0:l,0:9]


# Split our data
train, test, train_labels, test_labels = train_test_split(features,
                                                            labels,
                                                            test_size=0.33,
                                                            random_state= 42)#

  # Initialize our classifier
gnb = GaussianNB()

  # Train our classifier
model = gnb.fit(train, train_labels)
preds = gnb.predict(test)

print("No of Attack Free graphs-------->"+str(test_labels.count(1)))
print("No of Attacked graphs--------->"+str(test_labels.count(0)))

  
  # Evaluate accurac
print(accuracy_score(test_labels, preds))

cm = confusion_matrix(test_labels, preds)

cm = cm.T

print(cm)



No of Attack Free graphs-------->30
No of Attacked graphs--------->692
0.8850415512465374
[[609   0]
 [ 83  30]]


In [ ]:
# cm = [[246,   1],
#  [ 38 ,  4]]


tp = cm[0][0]
tn = cm[1][1]
fp = cm[0][1]
fn = cm[1][0]

re = tp/(tp+fn)
pr = tp/(tp+fp)
f1 = 2*pr*re/(pr+re)
fpr = fp / (fp+tn)
print("pr.........."+str(pr))
print("re----"+str(re))

print("f1===="+str(f1))
print("fpr====="+ str(fpr))
print((tp+tn)/(tp+tn+fp+fn))

pr..........1.0
re----0.880057803468208
f1====0.9362029208301307
fpr=====0.0
0.8850415512465374


In [ ]:
1321
287306
0.9715168712559809
[[280236   1151]
 [  7070    170]]
5 messages


1196
143118
0.9342059675429966
[[134418    795]
 [  8700    401]]
 10


 449
13983
0.8810975609756098
[[12296    29]
 [ 1687   420]]
 100


 226
6990
0.8842849223946785
[[6157    2]
 [ 833  224]]

 200


 91
2796
0.8732248008313128
[[2430    0]
 [ 366   91]]
 500


 47
1397
0.8704986149584487
[[1210    0]
 [ 187   47]]
 1000


 30
692
0.8850415512465374
[[609   0]
 [ 83  30]]
 2000


 5
284
0.8650519031141869
[[246   1]
 [ 38   4]]
 5k



 5
140
0.8482758620689655
[[118   0]
 [ 22   5]]
 10k

In [ ]:
pr..........0.995909548060145
re----0.9753920906629169
f1====0.9855440457329349
0.9715168712559809
5 messages


pr..........0.9941203878325309
re----0.9392110007126986
f1====0.9658859415587915
0.9342059675429966
10 messages

pr..........0.9976470588235294
re----0.8793535006793964
f1====0.9347726927170442
0.8810975609756098
100

pr..........0.9996752719597337
re----0.8808297567954221
f1====0.936497072020686
0.8842849223946785
200


pr..........1.0
re----0.869098712446352
f1====0.9299655568312285
0.8732248008313128
500


pr..........1.0
re----0.8661417322834646
f1====0.9282700421940928
0.8704986149584487
1000


pr..........1.0
re----0.880057803468208
f1====0.9362029208301307
0.8850415512465374
2000


pr..........0.9959514170040485
re----0.8661971830985915
f1====0.9265536723163843
0.8650519031141869
5k


pr..........1.0
re----0.8428571428571429
f1====0.9147286821705426
0.8482758620689655
10k