In [ ]:
4621

4621

In [1]:
!unzip /content/RPM_dataset.zip

Archive:  /content/RPM_dataset.zip
  inflating: RPM_dataset.csv         


In [4]:
import numpy as np

attackFreeArray = []
file = open('/content/RPM_dataset.csv', 'r')
attackList = []
counter = 0
graphList = []
ultimateGraphList = [] 
uttimateDetectionList = []
graphCounter = 0

noOfMessages = 200
for line in file:
  Xpartition = line.split()[0].split(',')
  attackList.append(Xpartition[len(Xpartition)-1])

  
  node = Xpartition[1]

  graphList.append(node)
  if len(graphList) == noOfMessages: #No of messages
    ultimateGraphList.append(graphList)
    uttimateDetectionList.append(attackList)

    # ultimateGraphList.append(graphList)
    # uttimateDetectionList.append(attackList)

    # ultimateGraphList.append(graphList)
    # uttimateDetectionList.append(attackList)

    # ultimateGraphList.append(graphList)
    # uttimateDetectionList.append(attackList)

    # ultimateGraphList.append(graphList)
    # uttimateDetectionList.append(attackList)

    # ultimateGraphList.append(graphList)
    # uttimateDetectionList.append(attackList)
  
    graphCounter+=1    
    graphList = []
    attackList = []
  

ugl = ultimateGraphList
udl = uttimateDetectionList

print(attackFreeArray.count(0))

print(len(graphList))
print(len(ugl))
print(ugl[3])
print(len(udl))
print(udl[0])
print(graphCounter)


0
102
23108
['0002', '0153', '0130', '0131', '0140', '043f', '0370', '0440', '0350', '0316', '018f', '0260', '02a0', '0329', '04f0', '0545', '02c0', '0430', '04b1', '01f1', '0153', '0002', '00a0', '00a1', '0130', '0131', '0140', '0370', '043f', '0440', '0350', '0316', '018f', '0260', '02a0', '0329', '0545', '02c0', '0002', '0153', '0130', '0131', '0140', '043f', '0370', '0440', '0350', '04f0', '0316', '018f', '0260', '02a0', '0329', '0545', '02c0', '0430', '04b1', '01f1', '0153', '0002', '0130', '0131', '0140', '0370', '043f', '0440', '0350', '0316', '018f', '0260', '02a0', '0329', '0545', '02c0', '0002', '0153', '0130', '0131', '0140', '043f', '0370', '0440', '0350', '0316', '018f', '0260', '02a0', '0329', '04f0', '0545', '05f0', '02c0', '0430', '04b1', '01f1', '0153', '0002', '0130', '0131', '0140', '0370', '043f', '0440', '0350', '0316', '018f', '0260', '02a0', '0329', '0545', '02c0', '0002', '0153', '0130', '0131', '0140', '043f', '0370', '0440', '0350', '04f0', '018f', '0260', '02

In [6]:
#Making graph from the 200 sequential of id and store them in a file as Graph adjacent list
from collections import defaultdict
import networkx as nx
import matplotlib.pyplot as plt
import random

gAttackfree=nx.DiGraph()
gAttacked = nx.DiGraph()
lenugl = len(ugl)

fileW = open("rpmAttackGraph.txt","w")

counter = 0
gAttackfreeCounter = 0
gAttackedCounter = 0

isNotDone1 = True
isNotDone2 = True 
gAttackfree=nx.DiGraph()
gAttacked = nx.DiGraph()

for i in range(0,lenugl):
  fileW.write("Graph No: "+str(i+1))
  fileW.write("\n")
  dicGraph = defaultdict(list)
  attackFree = 1

  

  for j in range (0, len(ugl[i])-1):
    dicGraph[str(ugl[i][j])].append((ugl[i][j+1]))
   

  
  for j in range(len(udl[i])):
    if udl[i][j] == 'T':
      attackFree = 0

      
  
  if attackFree == False and isNotDone1 == True:
    gAttackedCounter = i
    for j in range (0, len(ugl[i])-1):
      gAttacked.add_edge(ugl[i][j], ugl[i][j+1])
    isNotDone1 = False
    
  if attackFree == True and isNotDone2 == True:
    gAttackfreeCounter = i
    for j in range (0, len(ugl[i])-1):
      gAttackfree.add_edge(ugl[i][j], ugl[i][j+1])
    isNotDone2 = False
    


  

  
  fileW.write("Attack Free: "+str(attackFree)+"\n")

  for key, val in dicGraph.items():
    fileW.write(str(key) + (" ---> "))
    for m in range(0, len(val)):
      fileW.write(val[m]+"\t")
    fileW.write("\n")


print(counter)
print(gAttackfreeCounter)
print(gAttackedCounter)

fileW.close()

#print(len(list(gAttackfree)))


0
0
8


In [7]:
#Getting all the features

import networkx as nx
import hashlib
import numpy as np

#Function for tracing the attacked and attackfree graph. Return a list which 
#contation the info that a graph is attacked or attack
def getAttackFreelist(filename):
  attacFreekList = []
  file_ = open(filename, 'r')


  graphCounter = 0
  while True: 
  
    # Get next line from file 
      line = file_.readline() 
  
    # if line is empty 
    # end of file is reached 
      if not line: 
          break
    

    
      graph_number = line[0:5]
    
      if graph_number == "Graph":
      #print(graph_number+str(graphCounter))
        graphCounter += 1
        line = file_.readline()
        attacFreekList.append(line.split())

  
  file_.close()
  print(len(attacFreekList))
  print(attacFreekList)
  return attacFreekList


def getFeatures(filename):

  attackFreeList = getAttackFreelist(filename)
  file_ = open(filename, 'r')

  graphList = []
  ultimate_graphList = []  
  graphCounter = 0
  while True: 
  
    # Get next line from file 
      line = file_.readline() 
  
    # if line is empty 
    # end of file is reached 
      if not line: 
          break
    

    
      graph_number = line[0:5]
    
      if graph_number == "Graph":
      #print(graph_number+str(graphCounter))
        graphCounter += 1
        line = file_.readline()
        line = file_.readline()

        if graphCounter >= 2:
          ultimate_graphList.append(graphList)
          graphList = []


    
      list1 = line.split()
      graphList.append(list1)



  ultimate_graphList.append(graphList)
    
  file_.close()

  list_All_Feature_Set = []
 
  filetowrite = filename[:-4]+"_GraphFeatures.txt"
  file1 = open(filetowrite,'w')

  graphNumber = len(ultimate_graphList)
# Iterating every graph
  for i in range(0,graphNumber):

    G = nx.DiGraph()
    graphEdgeNumber = len(ultimate_graphList[i])
     # defining variable for detecting max pagerank
  #making the graph
    indegree = 0
    outdegree = 0
    
    for j in range(0,graphEdgeNumber):
      vertexConnectionLength = len(ultimate_graphList[i][j])

      for k in range(2,vertexConnectionLength):
      
      
        G.add_edge(ultimate_graphList[i][j][0],ultimate_graphList[i][j][k])
    

    weighted_Feature_Set = nx.pagerank(G)
    
    edge = G.number_of_edges()
    node = G.number_of_nodes()

    
    temp_list = list(weighted_Feature_Set.values())
    median_pagerank_vertices = np.median(temp_list)
    maximum_pagerank_vertex = np.max(temp_list)
    minimum_pagerank_vertex = np.min(temp_list)
    std_pagerank = np.std(temp_list)
    varpagerank = np.var(temp_list)


    if i == 0:
      file1.write("No."+"\t"+"Nodes\t"+"Edges\t"+"MaximumIndegree\t"+"MinimumIndegree\t"+"MaximumOutdegree\t"+
                  "MinimumOutdegree\t"+	
                  "MedianPagerank\t"+"MaximumPagerank\t"+"MininumPagerank\t"+"StdPageRank\t"+
                  "VarPageRank\t"+"State\n")

    file1.write(str(i+1)+"\t")
    counter = 0
    in_deg = []
    out_deg = []
    for key,val in weighted_Feature_Set.items():
      in_deg.append(G.in_degree(key))
      out_deg.append(G.out_degree(key))
    
    maxInd = np.max(in_deg)
    minInd = np.min(in_deg)
    maxOut = np.max(out_deg)
    minOut = np.min(out_deg)
    file1.write(str(node)+"\t") 
    file1.write(str(edge)+"\t")
    file1.write(str(maxInd)+str("\t")+str(minInd)+str("\t"))
    file1.write(str(maxOut)+str("\t")+str(minOut)+str("\t"))
    
    file1.write(str(median_pagerank_vertices)+str("\t")+str(maximum_pagerank_vertex))
    file1.write(str("\t")+str(minimum_pagerank_vertex)+str("\t")+str(std_pagerank)+"\t"+
                str(varpagerank)+"\t"+
                str(attackFreeList[i][2])+"\n")

  


  file1.close()
getFeatures('/content/rpmAttackGraph.txt')



23108
[['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '1'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Attack', 'Free:', '0'], ['Att

In [ ]:
#Applying the GNB and getting the accuracy and confusion matrix

import seaborn as sn
import matplotlib.pyplot as plt
import pandas
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


# load dataset
dataframe = pandas.read_table('/content/rpmAttackGraph_GraphFeatures.txt')
data = dataframe.drop("No.", axis=1)
data = data.drop("StdPageRank", axis=1)
data = data.drop("VarPageRank", axis=1)
dataset = data.values



# split into input (X) and output (Y) variables


l = len(ugl)
X = dataset[:,0:]
# print(X.shape)
labels = []
for i in range (0,l):
  if X[i][9] == True:
    labels.append(0)
  else:
    labels.append(1)

features = X[0:l,0:9]


# Split our data
train, test, train_labels, test_labels = train_test_split(features,
                                                            labels,
                                                            test_size=0.33,
                                                            random_state= 42)#

  # Initialize our classifier
gnb = GaussianNB()

  # Train our classifier
model = gnb.fit(train, train_labels)
preds = gnb.predict(test)

print(test_labels.count(1))
print(test_labels.count(0))

  
  # Evaluate accurac
print(accuracy_score(test_labels, preds))

cm = confusion_matrix(test_labels, preds)

cm = cm.T

print(cm)



433
330
0.9829619921363041
[[326   9]
 [  4 424]]


In [ ]:
124468
180565
0.8499441044083755
[[180464  45671]
 [   101  78797]]
 5

 67868
84649
0.9822314889487729
[[84151  2212]
 [  498 65656]]
 10

6913
8339
0.9975740886441122
[[8335   33]
 [   4 6880]]
 100

3554
4072
0.9959349593495935
[[4062   21]
 [  10 3533]]
 200


2320
2764
0.9954760031471283
[[2758   17]
 [   6 2303]]
300

1776
2037
0.996590611067401
[[2034   10]
 [   3 1766]]
400

 1446
1605
0.9914782038675845
[[1596   17]
 [   9 1429]]
 500


1253
1289
0.9940991345397325
[[1283    9]
 [   6 1244]]
 600

 777
748
0.9895081967213115
[[739   7]
 [  9 770]]
 1k


433
330
0.9829619921363041
[[326   9]
 [  4 424]]
 2k

 234
71
0.9508196721311475
[[ 71  15]
 [  0 219]]
 5k

 120
33
0.9869281045751634
[[ 33   2]
 [  0 118]]
 10k

In [ ]:
# cm =[[ 71,  15],
#  [  0 ,219]]

tp = cm[0][0]
tn = cm[1][1]
fp = cm[0][1]
fn = cm[1][0]

re = tp/(tp+fn)
pr = tp/(tp+fp)
f1 = 2*pr*re/(pr+re)
fpr = fp/(fp+tn)

print("pr.........."+str(pr))

print("re----"+str(re))

print("f1===="+str(f1))
print("fpr===="+str(fpr))
print((tp+tn)/(tp+tn+fp+fn))

pr..........0.9731343283582089
re----0.9878787878787879
f1====0.9804511278195489
fpr====0.020785219399538105
0.9829619921363041


In [ ]:
re----0.9994406446432033
pr..........0.7980365710748004
f1====0.8874551266289649
0.8499441044083755
5 messages

###################################################################

re----0.9941168826566174
pr..........0.9743871796950083
f1====0.9841531588426543
0.9822314889487729
10 messages

######################################
re----0.9995203261781989
pr..........0.9960564053537285
f1====0.997785359430179
0.9975740886441122
100 messages

#####################$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

re----0.9975442043222004
pr..........0.9948567229977957
f1====0.9961986511342734
0.9959349593495935
200 messages

######################################################

re----0.994392523364486
pr..........0.9894606323620583
f1====0.9919204474829085
0.9914782038675845
500 messages

##########################################################

re----0.9879679144385026
pr..........0.9906166219839142
f1====0.9892904953145917
0.9895081967213115
1k messages

#################################################

pr..........0.8255813953488372
re----1.0
f1====0.9044585987261146
fpr====0.0641025641025641
0.9508196721311475
5k messages

#######################################################
re----1.0
pr..........0.9428571428571428
f1====0.9705882352941176
0.9869281045751634
10k messages