In [7]:
#Applying the GNB and getting the accuracy and confusion matrix

import seaborn as sn
import matplotlib.pyplot as plt
import pandas
from sklearn.metrics import classification_report
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


# load dataset
dataframe = pandas.read_table('/content/mixedGraph_GraphFeatures_500.txt')

data = dataframe.drop("No.", axis=1)
data = data.drop("StdPageRank", axis=1)
data = data.drop("VarPageRank", axis=1)
dataset = data.values



# split into input (X) and output (Y) variables


l = len(dataframe)

X = dataset[:,0:]
# print(X.shape)
labels = []
for i in range (0,l):
  if X[i][9] == 'R':
    labels.append(0)
  elif X[i][9] == 'I':
    labels.append(1)
  elif X[i][9] == 'D':
    labels.append(2)
  elif X[i][9] == 'S':
    labels.append(3)
  elif X[i][9] == 'F':
    labels.append(4)

features = X[0:l,0:9]
print("Attacked--I----"+str(labels.count(1)))
print("Attacked---D-->"+str(labels.count(2)))
print("Attacked---S---"+str(labels.count(3)))
print("Attacked--F--->"+str(labels.count(4)))

# Split our data
train, test, train_labels, test_labels = train_test_split(features,
                                                            labels,
                                                            test_size=0.33,
                                                            random_state= 42)#

  # Initialize our classifier
gnb = GaussianNB()

  # Train our classifier
model = gnb.fit(train, train_labels)
preds = gnb.predict(test)
print("........Belows are for the test cases-----------")
print("Attackfree in test-->"+str(test_labels.count(0)))
print("I in test-->"+str(test_labels.count(1)))
print("D in test-->"+str(test_labels.count(2)))
print("S in test--->"+str(test_labels.count(3)))
print("F in test ---->"+str(test_labels.count(4)))

  
  # Evaluate accurac
print(accuracy_score(test_labels, preds))

cm = confusion_matrix(test_labels, preds)

cm = cm.T

print(cm)

target_names = ["Attack free", "Replay attacks", "DoS attacks", "Spoofing attacks", "Fuzzy attacks"]

print('classification report')

print(classification_report(test_labels, preds, target_names=target_names))



Attacked--I----266
Attacked---D-->2453
Attacked---S---4418
Attacked--F--->2865
........Belows are for the test cases-----------
Attackfree in test-->7590
I in test-->79
D in test-->813
S in test--->1465
F in test ---->943
0.9558310376492195
[[7231    0    8   15   10]
 [ 335   79    0    0    1]
 [   1    0  725    8    0]
 [   9    0   80 1442    0]
 [  14    0    0    0  932]]
classification report
                  precision    recall  f1-score   support

     Attack free       1.00      0.95      0.97      7590
  Replay attacks       0.19      1.00      0.32        79
     DoS attacks       0.99      0.89      0.94       813
Spoofing attacks       0.94      0.98      0.96      1465
   Fuzzy attacks       0.99      0.99      0.99       943

        accuracy                           0.96     10890
       macro avg       0.82      0.96      0.84     10890
    weighted avg       0.98      0.96      0.97     10890

